/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Feedback {
  'userId' : Principal,
  'submittedAt' : Time,
  'comment' : string,
  'rating' : bigint,
}
export interface QueueEntry {
  'status' : QueueEntryStatus,
  'userId' : Principal,
  'joinedAt' : Time,
}
export type QueueEntryStatus = { 'noShow' : null } |
  { 'cancelled' : null } |
  { 'served' : null } |
  { 'waiting' : null };
export interface Service {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createService' : ActorMethod<[string, string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQueueSnapshot' : ActorMethod<[bigint], Array<QueueEntry>>,
  'getQueueStatus' : ActorMethod<[bigint], bigint>,
  'getServiceFeedback' : ActorMethod<[bigint], Array<Feedback>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinQueue' : ActorMethod<[bigint], undefined>,
  'leaveQueue' : ActorMethod<[bigint], undefined>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'markNoShow' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'serveNext' : ActorMethod<[bigint], Principal>,
  'submitFeedback' : ActorMethod<[bigint, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];