/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const QueueEntryStatus = IDL.Variant({
  'noShow' : IDL.Null,
  'cancelled' : IDL.Null,
  'served' : IDL.Null,
  'waiting' : IDL.Null,
});
export const Time = IDL.Int;
export const QueueEntry = IDL.Record({
  'status' : QueueEntryStatus,
  'userId' : IDL.Principal,
  'joinedAt' : Time,
});
export const Feedback = IDL.Record({
  'userId' : IDL.Principal,
  'submittedAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createService' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQueueSnapshot' : IDL.Func([IDL.Nat], [IDL.Vec(QueueEntry)], ['query']),
  'getQueueStatus' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getServiceFeedback' : IDL.Func([IDL.Nat], [IDL.Vec(Feedback)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinQueue' : IDL.Func([IDL.Nat], [], []),
  'leaveQueue' : IDL.Func([IDL.Nat], [], []),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'markNoShow' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'serveNext' : IDL.Func([IDL.Nat], [IDL.Principal], []),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const QueueEntryStatus = IDL.Variant({
    'noShow' : IDL.Null,
    'cancelled' : IDL.Null,
    'served' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const Time = IDL.Int;
  const QueueEntry = IDL.Record({
    'status' : QueueEntryStatus,
    'userId' : IDL.Principal,
    'joinedAt' : Time,
  });
  const Feedback = IDL.Record({
    'userId' : IDL.Principal,
    'submittedAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createService' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQueueSnapshot' : IDL.Func([IDL.Nat], [IDL.Vec(QueueEntry)], ['query']),
    'getQueueStatus' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getServiceFeedback' : IDL.Func([IDL.Nat], [IDL.Vec(Feedback)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinQueue' : IDL.Func([IDL.Nat], [], []),
    'leaveQueue' : IDL.Func([IDL.Nat], [], []),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'markNoShow' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'serveNext' : IDL.Func([IDL.Nat], [IDL.Principal], []),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };